# This is a basic workflow that is manually triggered

name: Manual workflow


on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  update-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Code.gs
        run: node Code.gs
