name: Update YouTube Title

on:
  schedule:
    - cron: "*/3 * * * *"

jobs:
  update-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node updateTitle.js


